[project]
name = "investment-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fire>=0.7.0",
    "pymysql>=1.1.1",
    "sqlalchemy==2.0.29",
    "tqdm>=4.67.1",
    "tushare==1.2.89",
]
